[custom.all.idris2-pack-markdown]
type = "local"
path = "."
ipkg = "idris2-pack-markdown.ipkg"
test = "test/test.ipkg"

[custom.all.idris2-pack-markdown-test]
type = "local"
path = "test"
ipkg = "test.ipkg"